# Generated by Django 5.2 on 2025-05-01 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombre_etudiants', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
                ('type_salle', models.CharField(choices=[('CM', 'CM'), ('TD', 'TD'), ('TP', 'TP')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DisponibiliteEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PL.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_groupe', models.CharField(choices=[('CM', 'CM'), ('TD', 'TD'), ('TP', 'TP')], max_length=2)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PL.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PL.enseignant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PL.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('type_seance', models.CharField(choices=[('CM', 'CM'), ('TD', 'TD'), ('TP', 'TP')], max_length=2)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PL.enseignant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PL.groupe')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PL.module')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PL.salle')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibiliteSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PL.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_seance', models.CharField(choices=[('CM', 'CM'), ('TD', 'TD'), ('TP', 'TP')], max_length=2)),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PL.enseignant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PL.groupe')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PL.module')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PL.salle')),
            ],
        ),
    ]
