# Generated by Django 5.2 on 2025-05-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='semestre',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
