# Generated by Django 5.2 on 2025-05-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PL', '0002_filiere_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='semestre',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], max_length=10),
        ),
    ]
