# Generated by Django 5.2 on 2025-05-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PL', '0003_alter_filiere_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilitesalle',
            name='salle',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='DisponibiliteEnseignant',
        ),
        migrations.DeleteModel(
            name='DisponibiliteSalle',
        ),
    ]
